config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'users#index'
  	
  resources :users, except: [:show, :new]
  resources :workcenters, except: [:show, :new]

	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/upload', to: 'uploads#show'
  post '/upload', to: 'uploads#create'

  get '/schedule/:workcenter', to: 'jobs#index', as: 'schedule'
  get '/schedule', to: 'jobs#index', as: 'schedules'
  patch '/schedule/:workcenter', to: 'jobs#move'
  patch '/schedule', to: 'jobs#move'

  get '/settings', to: 'settings#edit'
  patch '/settings', to: 'settings#update'

end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :production
  belongs_to :workcenter

  def self.check_columns(columns)
    Job.upload_columns.any?{ |key, value| columns.include?(value)}
  end

  def self.upload_columns
    { 
      sequence: "Строка",
      start: "Начальная дата/время",
      end: "Конечная дата/время",
      info: "Инф-я план.",
      previous_quantity: "Good Qty (Previous Operation)",
      inks: "Color Code",
      number_ups: "#Ups",
      tools: "Used tools",
      operation: "Operation Id",
      produced: "Good Qty (Operation)",
      split_quantity: "Split Qty",
      outers: "Item Group (OU-1)",
      varnish_plate: "Varnish Plate Number",
      quantity: "Schedules Qty",
      varnish: "Varnish Code",
      part: "часть",
      fixed_date: "Фикс. дата",
      target_speed: "TargetSpeed",
      performance: "Performance (qty / h)",
      setup: "Время настройки",
      possible_workcenters: "штамп по машинам",
      operation_number: "№ опер.",
      dynamics_job: "JobId"
    }
  end

  def self.update_params(params, user)
    params[:start] = DateTime.strptime(params[:start], user.setting.time)
    params[:end] = DateTime.strptime(params[:end], user.setting.time)
    params[:fixed_date] ? params[:fixed_date] = DateTime.strptime(params[:fixed_date], user.setting.time) : nil
    params[:sequence] = params[:sequence].to_i * 10
    params[:previous_quantity] ? params[:previous_quantity] = params[:previous_quantity].delete(',').to_i : 0
    params[:number_ups] ? params[:number_ups] = params[:number_ups].delete(',').to_i : 0
    params[:produced] ? params[:produced] = params[:produced].delete(',').to_i : 0
    params[:split_quantity] ? params[:split_quantity] = params[:split_quantity].delete(',').to_i : 0
    params[:quantity] ? params[:quantity] = params[:quantity].delete(',').to_i : 0
    params[:part] ? params[:part] = params[:part].delete(',').to_i : 0
    params[:target_speed] ? params[:target_speed] = params[:target_speed].delete(',').to_i : 0
    params[:performance] ? params[:performance] = params[:performance].delete(',').to_i : 0
    params[:setup] ? params[:setup] = params[:setup].delete(',').to_d * 60 : 0
    params[:operation_number] ? params[:operation_number] = params[:operation_number].delete(',').to_i : 0
    params
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :current_user, :get_workcenter

  def index
    if params[:workcenter] = "first"
      params[:workcenter] = Workcenter.first.code
    end
    @jobs = @workcenter.get_jobs

  end

  def get_workcenter
    @workcenter = Workcenter.find_by(code: params[:workcenter])
    if !@workcenter 
      @workcenter = Workcenter.find_by(group: params[:workcenter])
    end
    if !@workcenter 
      @workcenter = Workcenter.first
    end
    @menu = @workcenter.menu
    @settings = @current_user.setting
  end

  def move
    position = Job.find_by(dynamics_job: move_params[:position])
    order = Job.find_by(dynamics_job: move_params[:order])
    order.update(sequence: position.sequence - 5)
    order.workcenter.calculate
    render json: {status: "OK"}
  end

  private

  def move_params
    params.require(:replace).permit(:position, :order)
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_header.html.haml
%ul{class: "menu align-left"}
  -@menu[:groups].each do |group|
    =link_to group, schedule_path(group), class: group == @workcenter.group ? "lawngreen button" : "khaki button"
%ul{class: "menu align-left"}
  -@menu[:workcenters].each do |workcenter|
    =link_to workcenter, schedule_path(workcenter), class: workcenter == @workcenter.code ? "lightcoral button" : "lightpink button"

app/views/jobs/index.html.haml
%table
  %thead
    %th #
    %th Start
    %th End
    %th Delivery
    %th Production
    %th Op.
    %th Name
    %th FG
    %th Quantity
    %th Previous
    %th Ready
    %th MR
    %th Performance
  %tbody
    -@jobs.map do |job|
      %tr{id: job.dynamics_job, draggable: "true", ondrop: "releaseLine(event)", ondragover: "allowDrop(event)", ondragstart: "drag(event)"}
        %td=job.sequence
        -if job.fixed_date == job.start
          %td{class: "nowrap fixed_good"}
            =job.start.strftime(@settings.time)
        -elsif job.fixed_date
          %td{class: "nowrap fixed_bad", title: job.fixed_date.strftime(@settings.time)}
            =job.start.strftime(@settings.time) 
        -else
          %td.nowrap=job.start.strftime(@settings.time)
        %td.nowrap=job.end.strftime(@settings.time)
        -if job.production.confirmed_date
          %td=job.production.confirmed_date.strftime(@settings.date)
        -elsif job.production.required_date
          %td=job.production.required_date.strftime(@settings.date)
        -else
          %td
        %td=job.production.order
        %td=job.operation
        %td.small=job.production.name
        %td=job.production.item
        %td=number_with_delimiter(job.quantity, delimiter: '.')
        %td=number_with_delimiter(job.previous_quantity, delimiter: '.')
        %td=number_with_delimiter(job.produced, delimiter: '.')
        %td=job.setup
        %td=number_with_delimiter(job.performance, delimiter: '.')
= javascript_include_tag "jobs", 'data-turbolinks-track': true