config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'users#index'
  	
  resources :users, except: [:show, :new]
  resources :workcenters, except: [:show, :new]

	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/upload', to: 'uploads#show'
  post '/upload', to: 'uploads#create'

  get '/schedule/:workcenter', to: 'jobs#index', as: 'schedule'
  get '/schedule', to: 'jobs#index', as: 'schedules'
  patch '/schedule/:workcenter', to: 'jobs#move'
  patch '/schedule', to: 'jobs#move'

  get '/settings', to: 'settings#edit'
  patch '/settings', to: 'settings#update'

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_one :setting

  before_destroy :check_last

  ROLES = ['User', "Viewer", 'Admin']
  validates :email, :name, presence: true, uniqueness: true
  validates :password, presence: true, on: :create
  validates :role, presence: true, inclusion: { in: ROLES }
  validate :password_complexity
  validate :at_least_one_admin, on: :update

  scope :admins, -> {where(role: "Admin")}


  def password_complexity
    if self.password
      symbols = 0
      if self.password.match(/[0-9]/)
        symbols += 10
      end
      if self.password.match(/[a-z]/)
        symbols += 26
      end
      if self.password.match(/[A-Z]/)
        symbols += 26
      end
      if self.password.match(/[$&+,:;=?@#|'<>.^*()%!-]/)
        symbols += 22
      end
      if self.password.length**symbols < 7237005577332262213973186563042994240829374041602535252466099000494570602496
        errors.add(:password, "should be more complex")
      end
    end
  end

  def at_least_one_admin
    admins = User.admins
    if !self.admin && admins.first == self && admins.count == 1
      errors.add("There", "should left at least one admin")
    end
  end

  def check_last
    admins = User.admins
    if admins.first == self && admins.count == 1
      errors.add("There", "should left at least one admin")
      throw(:abort)
    end
  end

  def admin
    self.role == 'Admin'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, :check_priveleges
  before_action :action_user, only: [:destroy, :update, :edit]


  def index
    @action_user = User.new
    @users = User.all
  end

  def edit
  
  end 

  def update
    if !user_params[:password]
      user_params.delete(:password)
      user_params.delete(:password_confirmation)
    end
    if @action_user.update(user_params)
      flash[:success] = "User updated successfully!"
      redirect_to users_path
    else
      flash.alert = @action_user.errors.messages
      redirect_to edit_user_path(@action_user)
    end
  end

  def destroy
    if  @action_user.destroy
      flash[:success] = "User deleted successfully!"
    else
      flash.alert = @action_user.errors.messages
    end
    redirect_to users_path
  end

  def create
    @action_user = User.new(user_params)   
    if @action_user.save
      flash[:success] = "Account created successfully!"
    else
      flash.alert = @action_user.errors.messages
    end
    redirect_to users_path
  end

private

  def user_params
    params.require(:user).permit(:name, :role, :email, :password, :password_confirmation)
  end

  def action_user
    @action_user = User.find(params[:id])
  end

  def check_priveleges
    redirect_to root_path, alert: 'Only Admin can access this page.' if !current_user.admin
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.haml
.half
  =form_for @action_user do |f|
    %fieldset.fieldset
      %legend Create new user:
      =f.label :name
      =f.text_field :name, autofocus: true
      =f.label :role
      =f.select :role, options_for_select(User::ROLES), selected: @action_user.role
      =f.label :email
      =f.email_field :email
      =f.label :password
      =f.password_field :password
      =f.label :password_confirmation
      =f.password_field :password_confirmation
      =f.submit class: "button"

app/views/users/edit.html.haml
%h1 
  ="Edit #{@action_user.name}"
= render @action_user

app/views/users/index.html.haml
%h1 All registered users
%table
  %thead
    %th Name
    %th Role
    %th Email
    %th Delete
    %th Edit
  %tbody
    -@users.map do |user|
      %tr
        %td 
          =user.name
        %td 
          =user.role
        %td 
          =user.email 
        %td 
          =link_to 'Delete', user_path(user), method: :delete, class: "alert button" 
        %td 
          =link_to 'Update', edit_user_path(user), class: "warning button" 
=render @action_user
    