config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'users#index'
  	
  resources :users, except: [:show, :new]
  resources :workcenters, except: [:show, :new]

	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/upload', to: 'uploads#show'
  post '/upload', to: 'uploads#create'

  get '/schedule/:workcenter', to: 'jobs#index', as: 'schedule'
  get '/schedule', to: 'jobs#index', as: 'schedules'
  patch '/schedule/:workcenter', to: 'jobs#move'
  patch '/schedule', to: 'jobs#move'

  get '/settings', to: 'settings#edit'
  patch '/settings', to: 'settings#update'

end

app/models/workcenter.rb
class Workcenter < ApplicationRecord

  has_many :jobs

  validates :code, format: { with: /\A[0-9]{3}\z/, message: "should consist of three digits" }

  scope :sorted, -> {order(:code)}
  scope :groups, -> {distinct.pluck(:group)}
  scope :get_for_group, -> (group){where(group: group).order(:code).pluck(:code)}


  def get_jobs
    self.jobs.includes(:production).order(:sequence)
  end

  def menu
    {
      groups: Workcenter.groups,
      workcenters: Workcenter.get_for_group(self.group)
    }
  end

  def set_start_date
    date = self.get_jobs.first.start
    date ? date : date = Time.now
    self.update(start_date: date)
  end

  def calculate
    jobs = self.jobs.order(:sequence)
    update_array = []
    jobs.each_with_index do |job, index|
      record = {id: job.id, created_at: Time.now, updated_at: Time.now}
      record[:sequence] = 10 * (index + 1)
      if index == 0
        record[:start] = self.start_date
      elsif job.fixed_date && job.fixed_date > update_array[index -1][:end]
        record[:start] = job.fixed_date
      else
        record[:start] = update_array[index -1][:end]
      end
      setup = job.setup ? job.setup : 0
      quantity = job.split_quantity - (job.produced ? job.produced : 0)
      record[:end] = record[:start] + (setup + (quantity / (job.performance / 60))).minutes
      update_array << record
    end
    Job.import(update_array, on_duplicate_key_update: [:sequence, :start, :end], validate: false, timestamps: false)
  end



end

app/controllers/workcenters_controller.rb
class WorkcentersController < ApplicationController

  before_action :authorize
  before_action :get_workcenter, only: [:destroy, :update]

  def index
    @workcenters = Workcenter.sorted
    session[:edit] ? @workcenter = Workcenter.find(session[:edit]) : @workcenter = Workcenter.new
    
  end

  def edit
    session[:edit] = params[:id]
    redirect_to workcenters_path
  end

  def update
    session[:edit] = nil
    if @workcenter.update(strong_params)
      flash[:success] = "Workcenter updated successfully!"
    else
      flash.alert = @workcenter.errors.messages
    end
    redirect_to workcenters_path
  end

  def create
    workcenter = Workcenter.new(strong_params)
    if workcenter.save
      flash[:success] = "Workcenter created successfully!"
    else
      flash.alert = workcenter.errors.messages
    end
    redirect_to workcenters_path
  end

  def destroy
    if  @workcenter.destroy
      flash[:success] = "Workcenter deleted successfully!"
    else
      flash.alert = @workcenter.errors.messages
    end
    redirect_to workcenters_path
  end

  private

  def get_workcenter
    @workcenter = Workcenter.find(params[:id])
  end

  def strong_params
    params.require(:workcenter).permit(:code, :name, :group, :description, :average_downtime, :frozen_period, :minimal_setup, :setup_reduction_type, :average_setup, :average_speed, :max_deviation)
  end

end

app/helpers/workcenters_helper.rb
module WorkcentersHelper
end

app/views/workcenters/_form.html.haml
%tr.nopadding
  %td=f.text_field :code, class: "nomargin"
  %td=f.text_field :name, class: "nomargin"
  %td=f.text_field :group, class: "nomargin"
  %td=f.text_area :description, class: "nomargin"
  %td=f.number_field :average_downtime, class: "nomargin"
  %td=f.number_field :frozen_period, class: "nomargin"
  %td=f.number_field :minimal_setup, class: "nomargin"
  %td=f.text_field :setup_reduction_type, class: "nomargin"
  %td=f.number_field :average_setup, class: "nomargin"
  %td=f.number_field :average_speed, class: "nomargin"
  %td=f.number_field :max_deviation, class: "nomargin"
  %td=f.submit class: "button tiny nomargin"

app/views/workcenters/_workcenter.html.haml
%tr
  %td=workcenter.code
  %td=workcenter.name
  %td=workcenter.group
  %td=workcenter.description
  %td=workcenter.average_downtime
  %td=workcenter.frozen_period
  %td=workcenter.minimal_setup
  %td=workcenter.setup_reduction_type
  %td=workcenter.average_setup
  %td=workcenter.average_speed
  %td=workcenter.max_deviation
  %td
    =link_to "Edit", edit_workcenter_path(workcenter.id), class: "warning tiny nomargin button"
    =link_to "Delete", workcenter, method: :delete, class: "alert tiny nomargin button"

app/views/workcenters/index.html.haml
%h1 All available workcenters
=form_for @workcenter do |f|
  %table
    %thead
      %th Code
      %th Name
      %th Group
      %th Description
      %th Downtime
      %th Frozen period
      %th Minimal Setup
      %th Setup Reduction type
      %th Average Setup
      %th Average Speed
      %th Max Deviation
      %th Edit
    %tbody
      -@workcenters.map do |workcenter|
        -if workcenter == @workcenter
          =render partial: 'form', locals: {f: f}
        -else
          =render workcenter
      -if !@workcenter.id
        =render partial: 'form', locals: {f: f}