config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'users#index'
  	
  resources :users, except: [:show, :new]
  resources :workcenters, except: [:show, :new]

	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/upload', to: 'uploads#show'
  post '/upload', to: 'uploads#create'

  get '/schedule/:workcenter', to: 'jobs#index', as: 'schedule'
  get '/schedule', to: 'jobs#index', as: 'schedules'
  patch '/schedule/:workcenter', to: 'jobs#move'
  patch '/schedule', to: 'jobs#move'

  get '/settings', to: 'settings#edit'
  patch '/settings', to: 'settings#update'

end

app/views/layouts/_messages.html.haml
-#  Rails flash messages styled for Zurb Foundation
- flash.each do |key, value|
  %div{ class: "callout #{key}", data: {closable: true}}
    - if value.respond_to?('each')
      - value.each do |subject, explanation|
        %p
          =subject
          - if explanation.kind_of?(Array)
            =explanation.join(', ')
          - else 
            =explanation
    - else
      %p 
        =value
    %button{class: "close-button", type: "button", aria: {label: "Dismiss alert"}, data: {close: true }}
      %span{aria: {hidden: "true"}}
        &times;
   

app/views/layouts/_navigation.html.haml
%nav.top-bar
  .top-bar-section
    %ul{class: "menu align-left"}
      = render 'layouts/navigation_links'
    -if current_page?(controller: 'jobs', action: 'index')
      = render 'jobs/header'
  .top-bar-right
    %ul{class: "vertical menu accordion-menu", data: {accordion: {menu: true}}}
      %li
        =link_to current_user.name, logout_path, method: :delete, class: "secondary button"


  

app/views/layouts/_navigation_links.html.haml
=link_to 'Workcenters', workcenters_path, class: "workcenters button"
=link_to 'Upload', upload_path, class: "upload button"
- if current_user.admin
  =link_to 'Users', users_path, class: "users button"
=link_to "Scedule", schedules_path, class: "workcenters button"
=link_to "Settings", settings_path, class: "workcenters button"

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= "Scheduler"

    = stylesheet_link_tag "application"
    = javascript_pack_tag "application", 'data-turbolinks-track': 'reload'
    = csrf_meta_tag

  %body
    - if current_user
      %header
        = render 'layouts/navigation'
    %main{role: "main"}
      = render 'layouts/messages'
    = yield